apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-chrome-332488
spec:
  replicas: 2
  selector:
    app: selenium-chrome-332488
  template:
    metadata:
      name: selenium-chrome-332488
      labels:
        app: selenium-chrome-332488
    spec:
      containers:
      - name: selenium-chrome-332488
        image: selenium/node-chrome:latest
        ports:
        - containerPort: 5555
        env:
        - name: HUB_HOST
          value: "selenium-hub-332488"
        - name: HUB_PORT
          value: "8100"
